language: python
python:
    - '2.7'
    - '3.5'
    - '3.6'
matrix:
    include:
        - python: 3.7
    dist: xenial
install:
    - pip install poetry tox-travis codecov
script:
    - tox
after_success:
    - codecov
