language: python
python:
    - '2.7'
    - '3.5'
    - '3.6'
matrix:
    include:
        - python: 3.7
    dist: xenial
before_install:
    - pip install poetry
install:
    - poetry install -v -E airflow
    - pip install tox-travis codecov
after_success:
    - codecov
script:
    - tox
